# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.api.admissionregistration_v1alpha1_api import AdmissionregistrationV1alpha1Api


class TestAdmissionregistrationV1alpha1Api(unittest.TestCase):
    """AdmissionregistrationV1alpha1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AdmissionregistrationV1alpha1Api()

    def tearDown(self) -> None:
        pass

    def test_create_mutating_admission_policy(self) -> None:
        """Test case for create_mutating_admission_policy

        """
        pass

    def test_create_mutating_admission_policy_binding(self) -> None:
        """Test case for create_mutating_admission_policy_binding

        """
        pass

    def test_delete_collection_mutating_admission_policy(self) -> None:
        """Test case for delete_collection_mutating_admission_policy

        """
        pass

    def test_delete_collection_mutating_admission_policy_binding(self) -> None:
        """Test case for delete_collection_mutating_admission_policy_binding

        """
        pass

    def test_delete_mutating_admission_policy(self) -> None:
        """Test case for delete_mutating_admission_policy

        """
        pass

    def test_delete_mutating_admission_policy_binding(self) -> None:
        """Test case for delete_mutating_admission_policy_binding

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    def test_list_mutating_admission_policy(self) -> None:
        """Test case for list_mutating_admission_policy

        """
        pass

    def test_list_mutating_admission_policy_binding(self) -> None:
        """Test case for list_mutating_admission_policy_binding

        """
        pass

    def test_patch_mutating_admission_policy(self) -> None:
        """Test case for patch_mutating_admission_policy

        """
        pass

    def test_patch_mutating_admission_policy_binding(self) -> None:
        """Test case for patch_mutating_admission_policy_binding

        """
        pass

    def test_read_mutating_admission_policy(self) -> None:
        """Test case for read_mutating_admission_policy

        """
        pass

    def test_read_mutating_admission_policy_binding(self) -> None:
        """Test case for read_mutating_admission_policy_binding

        """
        pass

    def test_replace_mutating_admission_policy(self) -> None:
        """Test case for replace_mutating_admission_policy

        """
        pass

    def test_replace_mutating_admission_policy_binding(self) -> None:
        """Test case for replace_mutating_admission_policy_binding

        """
        pass


if __name__ == '__main__':
    unittest.main()
