# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.api.version_api import VersionApi


class TestVersionApi(unittest.TestCase):
    """VersionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VersionApi()

    def tearDown(self) -> None:
        pass

    def test_get_code(self) -> None:
        """Test case for get_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
