# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.api.authentication_v1_api import AuthenticationV1Api


class TestAuthenticationV1Api(unittest.TestCase):
    """AuthenticationV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_self_subject_review(self) -> None:
        """Test case for create_self_subject_review

        """
        pass

    def test_create_token_review(self) -> None:
        """Test case for create_token_review

        """
        pass

    def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass


if __name__ == '__main__':
    unittest.main()
